Repository DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS, pull requests merged in 2022-12, with the labels that each got.

#234 ♻️코스 API 호출 상황 리펙터
  Resources/LaunchScreen.storyboard
  Resources/Lotties/splash.json
  Sources/App/AppCoordinator.swift
  Sources/App/AppDelegate.swift
  Sources/Core/LoadingIndicator.swift
  Sources/Data/Review/AddReview/AddReviewRepositoryImpl.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewController.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewModel.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewModel.swift
  Sources/Presenter/Profile/Profile/ProfileViewController.swift
  Sources/Presenter/Profile/Profile/ProfileViewModel.swift
  Sources/Presenter/Splash/SplashViewController.swift
  Sources/Presenter/Splash/SplashViewModel.swift
  SupportingFiles/ComeIt-Info.plist
Labels: 🎹Charlie

#240 ♻️리뷰 작성 화면에서 deleteCourse API 호출 수정
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
Labels: 🎹Charlie

#242 ♻️홈화면 코스등록 플로우(오늘부분) 분기처리 수정 및 티켓, 디데이수정 백그라운드 블러 적용
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketEmptyView.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
  Sources/Presenter/Profile/Profile/View/EditDateView.swift
Labels: 🌳Youth, Sub Task, Sprint2

#250 ♻️Youth 1차 QA수정
  Sources/DesignSystem/Views/Calendar/CalendarView.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Profile/Logout/UserWarning/UserWarningViewController.swift
Labels: 🌳Youth, 🐛버그, Sub Task

#245 ✨ 이미지 없을 때, 처리 & 이미지 뷰어(이미지 확대 기능) 추가
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Log/LogImageFullScreen/Cell/FullScreenImageCollectionViewCell.swift
  Sources/Presenter/Log/LogImageFullScreen/ViewController/LogImageFullScreenViewController.swift
  Sources/Presenter/Log/LogImageFullScreen/ViewModel/LogImageFullScreenViewModel.swift
  Sources/Presenter/Log/LogTicket/Cell/LogImageCollectionViewCell.swift
  Sources/Presenter/Log/LogTicket/View/EmptyImageView.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
  Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
  Sources/Presenter/Log/LogTicket/ViewModel/LogTicketViewModel.swift
Labels: 🗿Lumi, ✨기능 추가, Main Task, Sprint2

#254 ♻️ 1차 QA수정사항 반영
  Sources/App/AppCoordinator.swift
  Sources/App/AppDelegate.swift
  Sources/Presenter/Intro/Scenes/FindPlanet/FindPlanetViewModel.swift
  Sources/Presenter/Profile/Logout/UserWarning/UserWarningViewController.swift
Labels: 🛸Kyu

#253 ♻️ 1차 QA수정사항 반영
  Sources/Presenter/Log/LogTicket/View/EmptyImageView.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketEmptyView.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketLabel.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
  Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
  Sources/Presenter/Log/LogTicket/ViewModel/LogTicketViewModel.swift
Labels: 🗿Lumi, 🐛버그, Sub Task

#251 ♻️1차 QA 수정사항 반영
  Sources/Data/Review/EditReview/EditReviewRepositoryImpl.swift
  Sources/Presenter/Home/Course/View/CourseComplete/CourseCompleteViewController.swift
  Sources/Presenter/Home/Course/View/RegisterReview/Cell/AddImageCell.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewModel.swift
  Sources/Presenter/Home/MyHome/HomeAPIService.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
  Sources/Presenter/Profile/Profile/Cell/ProfileTableViewActivityCell.swift
  Sources/Presenter/Profile/Profile/ProfileViewController.swift
  Sources/Utility/Base/BaseViewController.swift
  Sources/Utility/Extensions/UIImagePickerController+.swift
Labels: 🎹Charlie

#257 🐛 LogTicket dismiss button bug 해결
  Sources/Presenter/Log/LogTicket/View/LogTicketEmptyView.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
  Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
Labels: 🗿Lumi, 🐛버그, Sub Task
