Repository DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS, pull requests merged in 2022-11, with the labels that each got.

#117 ✨프로필 화면 UI 구현
  Resources/Assets.xcassets/home_course/nav_chevron_left.imageset/Contents.json
  Resources/Assets.xcassets/home_course/nav_chevron_left.imageset/chevron_left.png
  Resources/Assets.xcassets/home_course/nav_chevron_left.imageset/chevron_left@2x.png
  Resources/Assets.xcassets/home_course/nav_chevron_left.imageset/chevron_left@3x.png
  Resources/Colors.xcassets/grayD8D8D8.colorset/Contents.json
  Sources/DesignSystem/Color/Palette.swift
  Sources/DesignSystem/Font/Font.swift
  Sources/Presenter/Profile/EditDay/EditDayViewController.swift
  Sources/Presenter/Profile/EditDay/EditDayViewModel.swift
  Sources/Presenter/Profile/Profile/Cell/ProfileTableViewActivityCell.swift
  Sources/Presenter/Profile/Profile/Cell/ProfileTableViewServiceCell.swift
  Sources/Presenter/Profile/Profile/ProfileViewController.swift
  Sources/Presenter/Profile/Profile/ProfileViewModel.swift
  Sources/Presenter/Profile/Profile/View/ProfileTableViewHeaderView.swift
  Sources/Presenter/Profile/ProfileCoordinator.swift
  Sources/Utility/Constants/Constants.swift
  Sources/Utility/Protocols/NavigationBarConfigurable.swift
Labels: 🎹Charlie, ✨기능 추가, Main Task

#118 ♻️코스 등록 UI 변경
  .swiftlint.yml
  Resources/Colors.xcassets/whiteFFFBD9.colorset/Contents.json
  Resources/Lotties/main_star.json
  Resources/Lotties/middle_star.json
  Sources/Data/Place.swift
  Sources/DesignSystem/Color/Palette.swift
  Sources/DesignSystem/Views/BackgroundView/BackgroundView.swift
  Sources/DesignSystem/Views/BackgroundView/MediumStarBackgroundView.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseCoordinator.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/Cell/MapPlaceTableViewCell.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/View/PlaceDetailView.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/View/PlaceListView.swift
  Sources/Presenter/Home/AddCourse/AddCourseTitle/AddCourseTitleViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseTitle/AddCourseTitleViewModel.swift
  Sources/Presenter/Home/AddCourse/Components/Button/MainButton.swift
  Sources/Presenter/Home/AddCourse/Components/Button/SmallRectButton.swift
  Sources/Presenter/Home/AddCourse/Components/Label/PaddingLabel.swift
  Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
  Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextView.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/Cell/PlaceSearchTableViewCell.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewController.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewModel.swift
  Sources/Presenter/Home/AddCourse/RecordCourse/Cell/AddImageCell.swift
  Sources/Presenter/Home/AddCourse/RecordCourse/Cell/ImageCollectionViewCell.swift
  Sources/Presenter/Home/AddCourse/RecordCourse/RecordCourseViewController.swift
  Sources/Presenter/Home/AddCourse/RecordCourse/RecordCourseViewModel.swift
  Sources/Presenter/Home/AddCourse/RecordCourse/View/CustomToggleButton.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewModel.swift
  Sources/Presenter/Home/HomeCoordinator.swift
  Sources/Presenter/Home/HomeTestViewController.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Profile/ProfileTestViewController.swift
  Sources/Utility/Base/BaseViewController.swift
  Sources/Utility/Constants/Constants.swift
  Sources/Utility/Extensions/UITextField+.swift
  Sources/Utility/HapticManager/HapticManager.swift
  Sources/Utility/Protocols/NavigationBarConfigurable.swift
Labels: 🎹Charlie, Main Task, Sprint2

#129 ✨ Log Tap Navigation 연결
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Log/LogHome/LogHomeViewController.swift
  Sources/Presenter/Log/LogHome/LogHomeViewModel.swift
  Sources/Presenter/Log/LogTicket/LogTicketViewController.swift
  Sources/Presenter/Log/LogTicket/LogTicketViewModel.swift
  Sources/Presenter/Log/MyConstellation/MyConstellationViewController.swift
  Sources/Presenter/Log/MyConstellation/MyConstellationViewModel.swift
Labels: 🗿Lumi, ✨기능 추가, Main Task, Sprint2

#121 ✨[UI] Log탭의 TicketView UI구성 및 FeedTap 삭제
  Resources/Assets.xcassets/KyuandWoody.imageset/Contents.json
  Resources/Assets.xcassets/KyuandWoody.imageset/KyuandWoody.png
  Resources/Assets.xcassets/refresh.imageset/Contents.json
  Resources/Assets.xcassets/refresh.imageset/refresh_1x.png
  Resources/Assets.xcassets/refresh.imageset/refresh_2x.png
  Resources/Assets.xcassets/refresh.imageset/refresh_3x.png
  Resources/Colors.xcassets/pinkF09BA1.colorset/Contents.json
  Resources/Colors.xcassets/pinkFF0099.colorset/Contents.json
  Sources/App/AppCoordinator.swift
  Sources/DesignSystem/Color/Palette.swift
  Sources/Presenter/Feed/FeedCollectionViewCell.swift
  Sources/Presenter/Feed/FeedCoordinator.swift
  Sources/Presenter/Feed/FeedViewController.swift
  Sources/Presenter/Feed/FeedViewModel.swift
  Sources/Presenter/Feed/TagCollectionViewCell.swift
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Log/LogHome/LogHomeViewController.swift
  Sources/Presenter/Log/LogHome/LogHomeViewModel.swift
  Sources/Presenter/Log/LogTicket/LogTicketViewController.swift
  Sources/Presenter/Log/LogTicket/LogTicketViewModel.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketLabel.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
  Sources/Presenter/Log/MyConstellation/MyConstellationViewController.swift
  Sources/Presenter/Log/MyConstellation/MyConstellationViewModel.swift
  Sources/Presenter/Main/MainCoordinator.swift
Labels: 🗿Lumi, ✨기능 추가, Main Task

#139 🚑Mock data memo 추가
  Sources/Presenter/LogMap/LogMapViewModel.swift
Labels: 🎹Charlie

#134 ♻️ProfileView 디자인 변경에 따른 UI 수정
  Project.swift
  Resources/Assets.xcassets/empty_result_star.imageset/Contents.json
  Resources/Assets.xcassets/empty_result_star.imageset/empty_result_star.png
  Resources/Assets.xcassets/empty_result_star.imageset/empty_result_star@2x.png
  Resources/Assets.xcassets/empty_result_star.imageset/empty_result_star@3x.png
  Sources/DesignSystem/Button/MainButton.swift
  Sources/DesignSystem/Button/SmallRectButton.swift
  Sources/DesignSystem/Button/SmallRoundButton.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/View/EmptyResultView.swift
  Sources/Presenter/Profile/Profile/ProfileViewController.swift
  Sources/Presenter/Profile/Profile/ProfileViewModel.swift
  Sources/Presenter/Profile/Profile/View/ProfilePlanetView.swift
  Sources/Presenter/Profile/ProfileTestViewController.swift
  Sources/Presenter/Profile/ProfileTestViewModel.swift
  Sources/Utility/Constants/Constants.swift
Labels: 🎹Charlie, Sub Task, Sprint2

#148 ✨FCM 연동
  Project.swift
  Resources/GoogleService-Info.plist
  Sources/App/AppDelegate.swift
  SupportingFiles/ComeIt.entitlements
  Tuist/Dependencies.swift
Labels: 🎹Charlie, ✨기능 추가

#151 ✨Home API연결
  Resources/Assets.xcassets/AlarmButton_empty.imageset/AlarmButton.png
  Resources/Assets.xcassets/AlarmButton_empty.imageset/Contents.json
  Resources/Assets.xcassets/AlarmButton_notEmpty.imageset/AlarmButton_NotEmpty.png
  Resources/Assets.xcassets/AlarmButton_notEmpty.imageset/Contents.json
  Sources/Data/AddCourse/AddCourseResponse.swift
  Sources/Data/User.swift
  Sources/DesignSystem/Views/Calendar/CalendarView.swift
  Sources/DesignSystem/Views/Calendar/Extensions/Date+.swift
  Sources/Presenter/Home/HomeDTO/SelectedDateCourseDTO.swift
  Sources/Presenter/Home/HomeDTO/UserCourseInfoDTO.swift
  Sources/Presenter/Home/HomeDTO/UserInfoDTO.swift
  Sources/Presenter/Home/MyHome/HomeAPIService.swift
  Sources/Presenter/Home/MyHome/HomeTestViewController.swift
  Sources/Presenter/Home/MyHome/LogAPIService.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Presenter/Home/MyHome/Views/PathTableViewCell.swift
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Search/SearchViewModel.swift
  Sources/Presenter/Test/TestViewController.swift
  Sources/Utility/Class/StarMaker.swift
  Sources/Utility/Extensions/Int+.swift
  Sources/Utility/Extensions/String+.swift
  SupportingFiles/ComeIt-Info.plist
Labels: 🌳Youth, ✨기능 추가, Main Task, Sprint2

#152 ✨ LogTap 화면 연결
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
  Sources/Presenter/Log/LogHome/ViewModel/LogHomeViewModel.swift
  Sources/Presenter/Log/LogMap/View/ConstellationAnnotationView.swift
  Sources/Presenter/Log/LogMap/ViewController/LogMapViewController.swift
  Sources/Presenter/Log/LogMap/ViewModel/LogMapViewModel.swift
  Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
  Sources/Presenter/Log/LogTicket/ViewModel/LogTicketViewModel.swift
  Sources/Presenter/Log/MyConstellation/Cell/MyConstellationCollectionViewCell.swift
  Sources/Presenter/Log/MyConstellation/MyConstellationViewController.swift
  Sources/Presenter/Log/MyConstellation/ViewController/MyConstellationViewController.swift
  Sources/Presenter/Log/MyConstellation/ViewModel/MyConstellationViewModel.swift
  Sources/Presenter/Test/TestViewController.swift
Labels: 🗿Lumi, ✨기능 추가, Sprint2

#150 ✨ [UI] LogHome UI 구성
  Resources/Assets.xcassets/ic_list.imageset/Contents.json
  Resources/Assets.xcassets/ic_list.imageset/ic_list.png
  Resources/Assets.xcassets/ic_map.imageset/Contents.json
  Resources/Assets.xcassets/ic_map.imageset/ic_map.png
  Resources/Assets.xcassets/ic_ticket.imageset/Contents.json
  Resources/Assets.xcassets/ic_ticket.imageset/ic_ticket.png
  Sources/DesignSystem/Color/Palette.swift
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Log/LogHome/LogHomeViewController.swift
  Sources/Presenter/Log/LogHome/LogHomeViewModel.swift
  Sources/Presenter/Log/LogHome/VIew/LogCollectionViewCell.swift
  Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
  Sources/Presenter/Log/LogHome/ViewModel/LogHomeViewModel.swift
  Sources/Presenter/Log/LogMap/View/ConstellationAnnotationView.swift
  Sources/Presenter/Log/LogMap/ViewController/LogMapViewController.swift
  Sources/Presenter/Log/LogMap/ViewModel/LogMapViewModel.swift
  Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
  Sources/Presenter/Log/LogTicket/ViewModel/LogTicketViewModel.swift
  Sources/Presenter/Log/MyConstellation/Cell/MyConstellationCollectionViewCell.swift
  Sources/Presenter/Log/MyConstellation/MyConstellationViewController.swift
  Sources/Presenter/Log/MyConstellation/ViewController/MyConstellationViewController.swift
  Sources/Presenter/Log/MyConstellation/ViewModel/MyConstellationViewModel.swift
  Sources/Utility/Class/StarMaker.swift
Labels: 🗿Lumi, ✨기능 추가

#157 :sparkles: 타입별로 별자리생성,코스수정 분기처리
  Sources/Presenter/Home/AddCourse/AddCourseCoordinator.swift
  Sources/Presenter/Home/MyHome/HomeCoordinator.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Presenter/Home/MyHome/Views/PathTableFooter.swift
  Sources/Presenter/Home/MyHome/Views/PathTableViewCell.swift
  SupportingFiles/ComeIt-Info.plist
Labels: 🌳Youth, ✨기능 추가, Sub Task, Sprint2

#159 🚑Entity 수정
  Sources/Domain/Entity/PlanetEntity.swift
Labels: 🎹Charlie

#160 ✨ LogTap 코스를 호출하는 API작업 완료
  Sources/Data/Log/FetchConstellation/FetchConstellationDTO.swift
  Sources/Data/Log/FetchConstellation/FetchConstellationRepositoryImpl.swift
  Sources/Domain/Entity/CourseEntity.swift
  Sources/Domain/Entity/ReviewEntity.swift
  Sources/Domain/Log/FetchConstellation/FetchConstellationRepository.swift
  Sources/Domain/Log/FetchConstellation/FetchConstellationsUseCase.swift
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Log/LogHome/VIew/LogCollectionViewCell.swift
  Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
  Sources/Presenter/Log/LogHome/ViewModel/LogHomeViewModel.swift
  Sources/Presenter/Log/MyConstellation/Cell/MyConstellationCollectionViewCell.swift
  Sources/Presenter/Log/MyConstellation/ViewController/MyConstellationViewController.swift
  Sources/Presenter/Log/MyConstellation/ViewModel/MyConstellationViewModel.swift
  Sources/Utility/Class/StarMaker.swift
Labels: 🗿Lumi, ✨기능 추가, Main Task, Sprint2

#168 ♻️코스 등록 API, 플로우 수정
  Resources/Assets.xcassets/PlaceResultAnnotation.imageset/Contents.json
  Resources/Assets.xcassets/PlaceResultAnnotation.imageset/PlaceResultAnnotation.png
  Resources/Assets.xcassets/PlaceResultAnnotation.imageset/PlaceResultAnnotation@2x.png
  Resources/Assets.xcassets/PlaceResultAnnotation.imageset/PlaceResultAnnotation@3x.png
  Sources/Core/LocationManager.swift
  Sources/Data/NetworkingError.swift
  Sources/Data/Place.swift
  Sources/Data/PlaceSearch/DTO/KakaoGetAddressDTO.swift
  Sources/Data/PlaceSearch/DTO/KakaoPlaceSearchDTO.swift
  Sources/Data/PlaceSearch/PlaceSearchRepositoryImpl.swift
  Sources/Domain/DomainDummy.swift
  Sources/Domain/PlaceSearch/PlaceSearchUseCase.swift
  Sources/Presenter/Home/AddCourse/AddCourseCoordinator.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/View/PlaceDetailView.swift
  Sources/Presenter/Home/AddCourse/AddCourseTitle/AddCourseTitleViewController.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/Cell/PlaceSearchTableViewCell.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewController.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewModel.swift
  Sources/Presenter/Home/AddCourse/PlaceSearchResultMap/PlaceSearchResultMapViewController.swift
  Sources/Presenter/Home/AddCourse/PlaceSearchResultMap/PlaceSearchResultMapViewModel.swift
  Sources/Presenter/Home/AddCourse/PlaceSearchResultMap/View/PlaceSearchResultAnnotationView.swift
  Sources/Presenter/Log/LogMap/ViewModel/LogMapViewModel.swift
  Sources/Utility/Constants/Constants.swift
  Sources/Utility/Protocols/NavigationBarConfigurable.swift
Labels: 🎹Charlie, ✨기능 추가, Sprint2

#172 ✨HomeCoordinator와 하위 Coordinator 연결
  Sources/Data/Model/Course.swift
  Sources/Data/Model/CourseImage.swift
  Sources/Data/Model/Place.swift
  Sources/Data/Model/Planet.swift
  Sources/Data/Model/Tag.swift
  Sources/Data/Model/User.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseCoordinator.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseTitle/AddCourseTitleViewModel.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewModel.swift
  Sources/Presenter/Home/AddCourse/PlaceSearchResultMap/PlaceSearchResultMapViewModel.swift
  Sources/Presenter/Home/AddCourse/RecordCourse/RecordCourseViewModel.swift
  Sources/Presenter/Home/Course/Coordinator/AddCourseCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/AddPlanCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/CourseFlowCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/EditCourseCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/EditPlanCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/RegisterReviewCoordinator.swift
  Sources/Presenter/Home/Course/CourseRequestDTO.swift
  Sources/Presenter/Home/Course/View/Components/Annotation/PlaceSearchResultAnnotationView.swift
  Sources/Presenter/Home/Course/View/Components/Annotation/StarAnnotationView.swift
  Sources/Presenter/Home/Course/View/Components/Button/CustomToggleButton.swift
  Sources/Presenter/Home/Course/View/Components/Label/PaddingLabel.swift
  Sources/Presenter/Home/Course/View/Components/TextField/CustomTextField.swift
  Sources/Presenter/Home/Course/View/Components/TextField/CustomTextView.swift
  Sources/Presenter/Home/Course/View/CourseComplete/CourseCompleteViewController.swift
  Sources/Presenter/Home/Course/View/CourseComplete/CourseCompleteViewModel.swift
  Sources/Presenter/Home/Course/View/CourseMap/Cell/MapPlaceTableViewCell.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewController.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewModel.swift
  Sources/Presenter/Home/Course/View/CourseMap/View/PlaceDetailView.swift
  Sources/Presenter/Home/Course/View/CourseMap/View/PlaceListView.swift
  Sources/Presenter/Home/Course/View/CourseTitle/CourseTitleViewController.swift
  Sources/Presenter/Home/Course/View/CourseTitle/CourseTitleViewModel.swift
  Sources/Presenter/Home/Course/View/PlaceSearch/Cell/PlaceSearchTableViewCell.swift
  Sources/Presenter/Home/Course/View/PlaceSearch/PlaceSearchViewController.swift
  Sources/Presenter/Home/Course/View/PlaceSearch/PlaceSearchViewModel.swift
  Sources/Presenter/Home/Course/View/PlaceSearch/View/EmptyResultView.swift
  Sources/Presenter/Home/Course/View/PlaceSearchResultMap/PlaceSearchResultMapViewController.swift
  Sources/Presenter/Home/Course/View/PlaceSearchResultMap/PlaceSearchResultMapViewModel.swift
  Sources/Presenter/Home/Course/View/RegisterReview/Cell/AddImageCell.swift
  Sources/Presenter/Home/Course/View/RegisterReview/Cell/ImageCollectionViewCell.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewModel.swift
  Sources/Presenter/Home/HomeCoordinator.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Presenter/Main/MainCoordinator.swift
  Sources/Utility/Extensions/CLLocationCoordinate2D+.swift
Labels: 🎹Charlie, ✨기능 추가

#175 ✨행성나가기, 회원탈퇴 view및 api연결 flow 구현
  Resources/Assets.xcassets/EARTH.imageset/Contents.json
  Resources/Assets.xcassets/EARTH.imageset/EARTH.png
  Sources/App/AppDelegate.swift
  Sources/Presenter/Home/HomeDTO/SelectedDateCourseDTO.swift
  Sources/Presenter/Home/MyHome/HomeAPIService.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Presenter/Home/MyHome/Views/PathTableViewCell.swift
  Sources/Presenter/Profile/Logout/UserWarning/ExitAPIService.swift
  Sources/Presenter/Profile/Logout/UserWarning/RecoverUserInfoViewController.swift
  Sources/Presenter/Profile/Logout/UserWarning/UserWarningViewController.swift
Labels: 🌳Youth, ✨기능 추가, Sub Task, Sprint2

#171 ✨ Log탭에서 코스의 리뷰를 불러오는 API연동
  Sources/Data/Log/FetchConstellation/FetchConstellationDTO.swift
  Sources/Data/Log/FetchConstellation/FetchConstellationRepositoryImpl.swift
  Sources/Data/Log/FetchReview/FetchReviewDTO.swift
  Sources/Data/Log/FetchReview/FetchReviewRepositoryImpl.swift
  Sources/Domain/Entity/ReviewEntity.swift
  Sources/Domain/Log/FetchReview/FetchReviewRepository.swift
  Sources/Domain/Log/FetchReview/FetchReviewUseCase.swift
Labels: 🗿Lumi, ✨기능 추가, Main Task, Sprint2

#181 :sparkles: 화면전환 데이터 전달
  Sources/App/AppDelegate.swift
  Sources/Presenter/Home/HomeDTO/SelectedDateCourseDTO.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
Labels: 🌳Youth, ✨기능 추가, Sub Task, Sprint2

#188 ✨회원탈퇴/행성나가기 구현 및 연결, homeview 오류해결
  Sources/App/AppDelegate.swift
  Sources/DesignSystem/Views/Calendar/CalendarView.swift
  Sources/DesignSystem/Views/Calendar/DataSource/PresentCalendarDiffableDataSource.swift
  Sources/DesignSystem/Views/Calendar/Extensions/Date+.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Presenter/Profile/Logout/UserWarning/UserWarningViewController.swift
  Sources/Presenter/Profile/Profile/ProfileViewController.swift
  Sources/Presenter/Profile/Profile/ProfileViewModel.swift
  Sources/Presenter/Profile/ProfileCoordinator.swift
Labels: 🌳Youth, ✨기능 추가, 🐛버그, Sprint2

#189 ✨코스 플로우 구현
  Sources/Data/AddCourse/AddCourseDTO.swift
  Sources/Data/AddCourse/AddCourseError.swift
  Sources/Data/AddCourse/AddCourseRepositoryImpl.swift
  Sources/Data/Course/AddCourse/AddCourseRepositoryImpl.swift
  Sources/Data/Course/AddCourse/AddCourseRequest.swift
  Sources/Data/Course/AddCourse/AddCourseResponse.swift
  Sources/Data/Course/CourseRequestDTO.swift
  Sources/Data/Course/DeleteCourse/DeleteCourseRepositoryImpl.swift
  Sources/Data/Course/DeleteCourse/DeleteCourseRequest.swift
  Sources/Data/Course/EditCourse/EditCourseRepositoryImpl.swift
  Sources/Data/Course/EditCourse/EditCourseRequest.swift
  Sources/Data/Course/EditCourse/EditCourseResponse.swift
  Sources/Data/Model/Place.swift
  Sources/Data/NetworkingError.swift
  Sources/Data/PlaceSearch/PlaceSearchRepositoryImpl.swift
  Sources/Data/Review/AddReview/AddReviewRepositoryImpl.swift
  Sources/Data/Review/AddReview/AddReviewResponse.swift
  Sources/Data/Review/DeleteReview/DeleteReviewRepositoryImpl.swift
  Sources/Data/Review/EditReview/EditReviewRepositoryImpl.swift
  Sources/DesignSystem/Button/MainButton.swift
  Sources/Domain/AddCourse/AddCourseUseCase.swift
  Sources/Domain/Course/AddCourseUseCase.swift
  Sources/Domain/Course/DeleteCourseUseCase.swift
  Sources/Domain/Course/EditCourseUseCase.swift
  Sources/Domain/Course/Interface/AddCourseRepository.swift
  Sources/Domain/Course/Interface/DeleteCourseRepository.swift
  Sources/Domain/Course/Interface/EditCourseRepository.swift
  Sources/Domain/Review/AddReviewUseCase.swift
  Sources/Domain/Review/DeleteReviewUseCase.swift
  Sources/Domain/Review/EditReviewUseCase.swift
  Sources/Domain/Review/Interface/AddReviewRepository.swift
  Sources/Domain/Review/Interface/DeleteReviewRepository.swift
  Sources/Domain/Review/Interface/EditReviewRepository.swift
  Sources/Presenter/Home/Course/Coordinator/AddCourseCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/AddPlanCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/EditCourseCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/EditPlanCoordinator.swift
  Sources/Presenter/Home/Course/Coordinator/RegisterReviewCoordinator.swift
  Sources/Presenter/Home/Course/View/CourseComplete/CourseCompleteViewController.swift
  Sources/Presenter/Home/Course/View/CourseComplete/CourseCompleteViewModel.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewController.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewModel.swift
  Sources/Presenter/Home/Course/View/CourseMap/View/PlaceListView.swift
  Sources/Presenter/Home/Course/View/CourseTitle/CourseTitleViewController.swift
  Sources/Presenter/Home/Course/View/CourseTitle/CourseTitleViewModel.swift
  Sources/Presenter/Home/Course/View/PlaceSearch/PlaceSearchViewController.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewModel.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Presenter/Home/MyHome/Views/PathTableFooter.swift
  Sources/Presenter/Home/MyHome/Views/PathTableViewCell.swift
  Sources/Utility/Protocols/NavigationBarConfigurable.swift
Labels: 🎹Charlie, ✨기능 추가

#187 ✨프로필 화면 작업 (디데이 수정, 서비스 약관)
  Resources/Assets.xcassets/EditDateImage.imageset/Contents.json
  Resources/Assets.xcassets/EditDateImage.imageset/EditDateImage.png
  Resources/Assets.xcassets/EditDateImage.imageset/EditDateImage@2x.png
  Resources/Assets.xcassets/EditDateImage.imageset/EditDateImage@3x.png
  Sources/Presenter/Intro/Network/Users/UserService/Request/UserRequestModel.swift
  Sources/Presenter/Intro/Network/Users/UserService/Response/UserResponseModel.swift
  Sources/Presenter/Profile/Profile/Cell/ProfileTableViewActivityCell.swift
  Sources/Presenter/Profile/Profile/ProfileViewController.swift
  Sources/Presenter/Profile/Profile/ProfileViewModel.swift
  Sources/Presenter/Profile/Profile/View/EditDateView.swift
  Sources/Presenter/Profile/Profile/View/ProfilePlanetView.swift
  Sources/Presenter/Profile/ProfileCoordinator.swift
  Sources/Utility/Constants/Constants.swift
Labels: 🎹Charlie, ✨기능 추가

#192 ✨코스 계획, 계획한 코스 수정 API 연결
  Sources/Data/Review/AddReview/AddReviewRepositoryImpl.swift
  Sources/Data/Review/EditReview/EditReviewRepositoryImpl.swift
  Sources/Domain/Course/EditCourseUseCase.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewModel.swift
Labels: 🎹Charlie, ✨기능 추가

#179 :sparkles: LogTap UI 수정
  Sources/Presenter/Log/LogCoordinator.swift
  Sources/Presenter/Log/LogHome/VIew/LogCollectionViewCell.swift
  Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
  Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
  Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
Labels: 🗿Lumi, ✨기능 추가, Main Task

#195 ♻️코스 등록 UT 반영
  Sources/Data/PlaceSearch/PlaceSearchRepositoryImpl.swift
  Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewController.swift
Labels: 🎹Charlie

#206 ♻️ 서버url분기처리
  Sources/Core/APIManager.swift
  Sources/Data/Alarm/AlarmAPI.swift
  Sources/Data/Alarm/AlarmIdAPI.swift
  Sources/Data/Course/AddCourse/AddCourseRepositoryImpl.swift
  Sources/Data/Course/DeleteCourse/DeleteCourseRepositoryImpl.swift
  Sources/Data/Course/EditCourse/EditCourseRepositoryImpl.swift
  Sources/Data/Log/FetchConstellation/FetchConstellationRepositoryImpl.swift
  Sources/Data/Log/FetchReview/FetchReviewRepositoryImpl.swift
  Sources/Data/Review/AddReview/AddReviewRepositoryImpl.swift
  Sources/Data/Review/DeleteReview/DeleteReviewRepositoryImpl.swift
  Sources/Data/Review/EditReview/EditReviewRepositoryImpl.swift
  Sources/Presenter/Home/MyHome/HomeAPIService.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/Views/PathTableFooter.swift
  Sources/Presenter/Home/MyHome/Views/PathTableViewCell.swift
  Sources/Presenter/Profile/Logout/UserWarning/ExitAPIService.swift
  Sources/Utility/Extensions/Double+.swift
Labels: 🌳Youth, Sub Task

#212 ♻️탭바 3개로 수정
  Resources/Assets.xcassets/TabBarIcon/Contents.json
  Resources/Assets.xcassets/TabBarIcon/ic_home.imageset/Contents.json
  Resources/Assets.xcassets/TabBarIcon/ic_home.imageset/ic_home.png
  Resources/Assets.xcassets/TabBarIcon/ic_home.imageset/ic_home@2x.png
  Resources/Assets.xcassets/TabBarIcon/ic_home.imageset/ic_home@3x.png
  Resources/Assets.xcassets/TabBarIcon/ic_log.imageset/Contents.json
  Resources/Assets.xcassets/TabBarIcon/ic_log.imageset/ic_feed.png
  Resources/Assets.xcassets/TabBarIcon/ic_log.imageset/ic_feed@2x.png
  Resources/Assets.xcassets/TabBarIcon/ic_log.imageset/ic_feed@3x.png
  Resources/Assets.xcassets/TabBarIcon/ic_profile.imageset/Contents.json
  Resources/Assets.xcassets/TabBarIcon/ic_profile.imageset/ic_profile.png
  Resources/Assets.xcassets/TabBarIcon/ic_profile.imageset/ic_profile@2x.png
  Resources/Assets.xcassets/TabBarIcon/ic_profile.imageset/ic_profile@3x.png
  Resources/Assets.xcassets/ic_search.imageset/Contents.json
  Resources/Assets.xcassets/ic_search.imageset/ic_search.png
  Resources/Assets.xcassets/ic_search.imageset/ic_search@2x.png
  Resources/Assets.xcassets/ic_search.imageset/ic_search@3x.png
  Sources/Presenter/Main/MainCoordinator.swift
  Sources/Presenter/Search/SearchCoordinator.swift
  Sources/Presenter/Search/SearchViewController.swift
  Sources/Presenter/Search/SearchViewModel.swift
  Sources/Presenter/Test/TestViewController.swift
  Sources/Utility/Constants/Constants.swift
Labels: 🎹Charlie

#215 ♻️UI 기기 대응
  Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
  Sources/Presenter/Profile/Profile/View/EditDateView.swift
Labels: 🎹Charlie

#223 :sparkles: 알림버튼 분기처리
  Sources/Presenter/Home/HomeDTO/UserInfoDTO.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
Labels: 🌳Youth, ✨기능 추가, Sub Task, Sprint2

#226 🚨homeview에서 최신 dday라벨 배포 준비, DTO optional수정
  Sources/Presenter/Home/HomeDTO/UserInfoDTO.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
Labels: 🌳Youth, 🐛버그, Sub Task, Sprint2

#228 💄프로필뷰 수정 및 백그라운드블러 적용
  Sources/DesignSystem/Views/Calendar/CalendarView.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Profile/EditProfile/EditProfileViewController.swift
Labels: 🌳Youth, Sub Task
