Repository DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS, pull requests merged in 2022-10, with the labels that each got.

#2 🎉프로젝트 생성
  .gitignore
  Project.swift
  Resources/LaunchScreen.storyboard
  Sources/App/AppDelegate.swift
  Sources/Coordinator/CoordinatorDummy.swift
  Sources/Data/DataDummy.swift
  Sources/DesignSystem/DesignSystemDummy.swift
  Sources/Domain/DomainDummy.swift
  Sources/Presenter/Test/TestViewController.swift
  Sources/Presenter/Test/TestViewModel.swift
  Sources/Utility/Base/BaseViewController.swift
  Sources/Utility/Base/BaseViewModel.swift
  Sources/Utility/Constants/ConstantDummy.swift
  Sources/Utility/Extensions/ExtensionDummy.swift
  Sources/Utility/Protocols/ProtocolDummy.swift
  SupportingFiles/MatStar-Info.plist
  Tuist/Config.swift
  Tuist/Dependencies.swift
Labels: 🎹Charlie, ✨기능 추가

#4 ✨Xcode MVVM 템플릿, shell script 추가
  Templates/MVVM.xctemplate/TemplateIcon-1016.png
  Templates/MVVM.xctemplate/TemplateIcon-1016@2x.png
  Templates/MVVM.xctemplate/TemplateInfo.plist
  Templates/MVVM.xctemplate/___FILEBASENAME___/___FILEBASENAME___ViewController.swift
  Templates/MVVM.xctemplate/___FILEBASENAME___/___FILEBASENAME___ViewModel.swift
  Templates/set_template.sh
Labels: 🎹Charlie, ✨기능 추가

#12 ✨Assets 파일 추가 및 Tuist 설정 변경
  Project.swift
  Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Resources/Assets.xcassets/Contents.json
Labels: 🎹Charlie, ✨기능 추가

#16 ♻️PR_Template 레퍼런스 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🎹Charlie

#14 ✨SwiftLint 적용
  .swiftlint.yml
  Project.swift
  Scripts/SwiftLint/set_swiftlint.sh
  Scripts/Templates/MVVM.xctemplate/TemplateIcon-1016.png
  Scripts/Templates/MVVM.xctemplate/TemplateIcon-1016@2x.png
  Scripts/Templates/MVVM.xctemplate/TemplateInfo.plist
  Scripts/Templates/MVVM.xctemplate/___FILEBASENAME___/___FILEBASENAME___ViewController.swift
  Scripts/Templates/MVVM.xctemplate/___FILEBASENAME___/___FILEBASENAME___ViewModel.swift
  Scripts/Templates/set_template.sh
  Sources/Presenter/Test/TestViewController.swift
  Sources/Utility/Base/BaseViewController.swift
  Sources/Utility/Base/BaseViewModel.swift
  Tuist/ProjectDescriptionHelpers/Scripts.swift
Labels: 🎹Charlie, ✨기능 추가

#20 ➕Lottie dependency 추가
  Project.swift
  Tuist/Dependencies.swift
Labels: 🎹Charlie

#29 ✨Color, Font 추가
  .swiftlint.yml
  Resources/Colors.xcassets/Contents.json
  Resources/Colors.xcassets/grayC5C5C5.colorset/Contents.json
  Resources/Colors.xcassets/mainYellow.colorset/Contents.json
  Sources/DesignSystem/Color/Palette.swift
  Sources/DesignSystem/DesignSystemDummy.swift
  Sources/DesignSystem/Font/Font.swift
  Sources/Presenter/Home/HomeTestViewController.swift
  Sources/Utility/Extensions/CGColor+.swift
  Sources/Utility/Extensions/ExtensionDummy.swift
  Sources/Utility/Extensions/UIColor+.swift
  Sources/Utility/Extensions/UIFont+.swift
Labels: 🎹Charlie, ✨기능 추가

#35 ✚ 데이터구조와 MockData추가
  Resources/Assets.xcassets/LumiPlanet.imageset/Contents.json
  Resources/Assets.xcassets/LumiPlanet.imageset/LumiPlanet.png
  Resources/Assets.xcassets/MyPlanetImage.imageset/Contents.json
  Resources/Assets.xcassets/MyPlanetImage.imageset/MyPlanetImage.png
  Resources/Assets.xcassets/YouthPlanet.imageset/Contents.json
  Resources/Assets.xcassets/YouthPlanet.imageset/YouthPlanet.png
  Sources/Data/Course.swift
  Sources/Data/CourseImage.swift
  Sources/Data/DataDummy.swift
  Sources/Data/Place.swift
  Sources/Data/Planet.swift
  Sources/Data/Tag.swift
  Sources/Data/User.swift
Labels: 🌳Youth, Sub Task

#55 ✨[코스등록] 완성 화면 UI 구현
  Resources/Fonts/GmarketSansTTFBold.ttf
  Resources/Fonts/GmarketSansTTFLight.ttf
  Resources/Fonts/GmarketSansTTFMedium.ttf
  Resources/Lotties/star_lottie.json
  Sources/DesignSystem/Font/Font.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewModel.swift
  Sources/Utility/Constants/Constants.swift
  Sources/Utility/Extensions/UIFont+.swift
  SupportingFiles/MatStar-Info.plist
  Tuist/Dependencies.swift
Labels: 🎹Charlie, ✨기능 추가, Sub Task

#47 ✨코스 등록 UI 구현
  Resources/Assets.xcassets/delete_button.imageset/Contents.json
  Resources/Assets.xcassets/delete_button.imageset/delete_button.png
  Resources/Assets.xcassets/delete_button.imageset/delete_button@2x.png
  Resources/Assets.xcassets/delete_button.imageset/delete_button@3x.png
  Resources/Assets.xcassets/lock_closed.imageset/Contents.json
  Resources/Assets.xcassets/lock_closed.imageset/lock_closed.png
  Resources/Assets.xcassets/lock_closed.imageset/lock_closed@2x.png
  Resources/Assets.xcassets/lock_closed.imageset/lock_closed@3x.png
  Resources/Assets.xcassets/lock_open.imageset/Contents.json
  Resources/Assets.xcassets/lock_open.imageset/lock_open.png
  Resources/Assets.xcassets/lock_open.imageset/lock_open@2x.png
  Resources/Assets.xcassets/lock_open.imageset/lock_open@3x.png
  Resources/Colors.xcassets/gray252632.colorset/Contents.json
  Resources/Colors.xcassets/gray3B3C46.colorset/Contents.json
  Sources/DesignSystem/Color/Palette.swift
  Sources/Presenter/Home/AddCourse/Components/Button/SmallRoundButton.swift
  Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextView.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/Cell/AddImageCell.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/Cell/ImageCollectionViewCell.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewController.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewModel.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/View/CustomToggleButton.swift
  Sources/Utility/Constants/Constants.swift
  Sources/Utility/Extensions/UIDevice+.swift
  Sources/Utility/Extensions/UIView+.swift
Labels: 🎹Charlie, ✨기능 추가, Sub Task

#62 ✨[코스 등록] 지도 화면에서 추가한 장소 리스트 모달 구현
  Project.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/Cell/MapPlaceTableViewCell.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/View/PlaceListView.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/Cell/PlaceSearchTableViewCell.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewController.swift
  Sources/Utility/Constants/Constants.swift
Labels: 🎹Charlie, ✨기능 추가, Sub Task

#63 ♻️디자인 변경에 따른 NavigationBar UI 수정
  Resources/Assets.xcassets/home_course/circle_x.imageset/Contents.json
  Resources/Assets.xcassets/home_course/circle_x.imageset/circle_x.png
  Resources/Assets.xcassets/home_course/circle_x.imageset/circle_x@2x.png
  Resources/Assets.xcassets/home_course/circle_x.imageset/circle_x@3x.png
  Resources/Assets.xcassets/home_course/x_mark.imageset/x_mark.png
  Resources/Assets.xcassets/home_course/x_mark.imageset/x_mark@2x.png
  Resources/Assets.xcassets/home_course/x_mark.imageset/x_mark@3x.png
  Resources/Colors.xcassets/gray333333.colorset/Contents.json
  Sources/DesignSystem/Color/Palette.swift
  Sources/Presenter/Home/AddCourse/Components/Button/SmallRectButton.swift
  Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewController.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewController.swift
  Sources/Presenter/Home/HomeTestViewController.swift
  Sources/Presenter/Profile/ProfileTestViewController.swift
  Sources/Presenter/Search/SearchTestViewController.swift
  Sources/Utility/Constants/Constants.swift
  Sources/Utility/Protocols/NavigationBarConfigurable.swift
Labels: 🎹Charlie, Sub Task

#70 🚑NavigationBar Configure 에러 해결
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewController.swift
Labels: 🎹Charlie

#59 ✨3.0.0 코스를 상세하게 보여주는 피드 기본적인 UI
  Resources/Assets.xcassets/lakeImage.imageset/Contents.json
  Resources/Assets.xcassets/lakeImage.imageset/lakeimage.png
  Resources/Assets.xcassets/woodyPlanetImage.imageset/Contents.json
  Resources/Assets.xcassets/woodyPlanetImage.imageset/woodyPlanetImage.png
  Resources/Colors.xcassets/pinkEB97D9.colorset/Contents.json
  Resources/LaunchScreen.storyboard
  Sources/DesignSystem/Color/Palette.swift
  Sources/DesignSystem/Font/Font.swift
  Sources/Presenter/Feed/FeedCollectionViewCell.swift
  Sources/Presenter/Feed/FeedCoordinator.swift
  Sources/Presenter/Feed/FeedTestViewController.swift
  Sources/Presenter/Feed/FeedTestViewModel.swift
  Sources/Presenter/Feed/FeedViewController.swift
  Sources/Presenter/Feed/FeedViewModel.swift
  Sources/Presenter/Feed/TagCollectionViewCell.swift
  Sources/Presenter/Home/HomeTestViewController.swift
  Sources/Utility/Extensions/UILabel+.swift
Labels: 🗿Lumi, ✨기능 추가, Main Task

#79 ✨HomeView 새로운 디자인으로 재구현
  Resources/Assets.xcassets/Changwon.imageset/Changwon.png
  Sources/Presenter/Home/HomeCoordinator.swift
  Sources/Presenter/Home/MyHome/View/CarouselCollectionView.swift
  Sources/Presenter/Home/MyHome/View/CarouselCollectionViewCell.swift
  Sources/Presenter/Home/MyHome/View/CourseCollectionViewCell.swift
  Sources/Presenter/Home/MyHome/View/HomeDetailView.swift
  Sources/Presenter/Home/MyHome/ViewController/CoursesViewController.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
Labels: 🌳Youth, ✨기능 추가, Main Task

#66 ✨Search 탭 🍷
  Resources/Assets.xcassets/like_image.imageset/Contents.json
  Resources/Assets.xcassets/like_image.imageset/like_image.png
  Resources/Assets.xcassets/picture_sample.imageset/Contents.json
  Resources/Assets.xcassets/picture_sample.imageset/picture_sample.png
  Resources/Assets.xcassets/unlike_image.imageset/Contents.json
  Resources/Assets.xcassets/unlike_image.imageset/unlike_image.png
  Sources/Presenter/Home/AddCourse/Components/TextField/CustomTextField.swift
  Sources/Presenter/Main/MainCoordinator.swift
  Sources/Presenter/Search/Course/Components/CoursePlanetSegmentedControlView.swift
  Sources/Presenter/Search/Course/Components/FollowButton.swift
  Sources/Presenter/Search/Course/Components/LikeButton.swift
  Sources/Presenter/Search/Course/Components/SearchTextField.swift
  Sources/Presenter/Search/Course/CourseTableView.swift
  Sources/Presenter/Search/Course/CourseTableViewCell.swift
  Sources/Presenter/Search/Course/PlanetTableViewCell.swift
  Sources/Presenter/Search/PhotoImage/CourseImageCollectionViewCell.swift
  Sources/Presenter/Search/SearchCoordinator.swift
  Sources/Presenter/Search/SearchTestViewController.swift
  Sources/Presenter/Search/SearchTestViewModel.swift
  Sources/Presenter/Search/SearchViewController.swift
  Sources/Presenter/Search/SearchViewModel.swift
  Sources/Utility/Extensions/UITextField+.swift
Labels: 🛸Kyu

#88 ✨내정보조회 api연결
  Sources/Data/Course.swift
  Sources/Data/CourseImage.swift
  Sources/Data/Planet.swift
  Sources/Data/Tag.swift
  Sources/Data/User.swift
  Sources/Presenter/Home/HomeDTO/InquiryMyPlanetDTO.swift
  Sources/Presenter/Home/MyHome/HomeAPIService.swift
  Sources/Presenter/Home/MyHome/View/HomeDetailView.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  SupportingFiles/MatStar-Info.plist
Labels: 🌳Youth, ✨기능 추가, Main Task

#78 ✨코스 등록 플로우 UI 완성
  Resources/Assets.xcassets/home_course/circle_x.imageset/circle_x.png
  Resources/Assets.xcassets/home_course/circle_x.imageset/circle_x@2x.png
  Resources/Assets.xcassets/home_course/circle_x.imageset/circle_x@3x.png
  Resources/Assets.xcassets/nav_bar_delete_button.imageset/Contents.json
  Resources/Assets.xcassets/nav_bar_delete_button.imageset/delete_button.png
  Resources/Assets.xcassets/nav_bar_delete_button.imageset/delete_button@2x.png
  Resources/Assets.xcassets/nav_bar_delete_button.imageset/delete_button@3x.png
  Resources/Assets.xcassets/purple_planet.imageset/Contents.json
  Resources/Assets.xcassets/purple_planet.imageset/purple_planet.png
  Resources/Assets.xcassets/purple_planet.imageset/purple_planet@2x.png
  Resources/Assets.xcassets/purple_planet.imageset/purple_planet@3x.png
  Resources/Assets.xcassets/star_annotation.imageset/Contents.json
  Resources/Assets.xcassets/star_annotation.imageset/star_annotation.png
  Resources/Assets.xcassets/star_annotation.imageset/star_annotation@2x.png
  Resources/Assets.xcassets/star_annotation.imageset/star_annotation@3x.png
  Sources/Data/Place.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseCoordinator.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/View/PlaceDetailView.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/View/PlaceListView.swift
  Sources/Presenter/Home/AddCourse/AddCourseMap/View/StarAnnotationView.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewController.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/PlaceSearchViewModel.swift
  Sources/Presenter/Home/AddCourse/PlaceSearch/View/EmptyResultView.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/Cell/ImageCollectionViewCell.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewController.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewModel.swift
  Sources/Presenter/Home/HomeCoordinator.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Utility/Constants/Constants.swift
  Sources/Utility/Extensions/MKPointOfInterestCategory+.swift
  Sources/Utility/Protocols/NavigationBarConfigurable.swift
  SupportingFiles/MatStar-Info.plist
Labels: 🎹Charlie, ✨기능 추가, Main Task

#95 ✨[코스 등록] 사진 추가, 삭제 기능 구현
  Sources/Presenter/Home/AddCourse/RegisterCourse/Cell/ImageCollectionViewCell.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewController.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewModel.swift
  Sources/Utility/Extensions/UIImagePickerController+.swift
  SupportingFiles/MatStar-Info.plist
Labels: 🎹Charlie, ✨기능 추가, Sub Task

#96 ✨[홈] 선택한 장소들로 별자리를 그려주는 기능 추가
  Resources/Assets.xcassets/star.imageset/Contents.json
  Resources/Assets.xcassets/star.imageset/star.png
  Sources/App/AppCoordinator.swift
  Sources/DesignSystem/Assets/UIImage+.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewModel.swift
  Sources/Utility/Extensions/UIImage+.swift
  Sources/Utility/Extensions/UIView+.swift
  Sources/Utility/Protocols/StarCreatable.swift
Labels: 🗿Lumi, ✨기능 추가, Sub Task

#103 ♻️프로젝트 이름 변경
  Project.swift
  Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SupportingFiles/ComeIt-Info.plist
Labels: 🎹Charlie, Main Task

#94 ✨[홈] "1.2.0 친구 별자리"뷰 구현
  Resources/Assets.xcassets/Planet1.imageset/Contents.json
  Resources/Assets.xcassets/Planet1.imageset/Planet1.png
  Resources/Assets.xcassets/Planet2.imageset/Contents.json
  Resources/Assets.xcassets/Planet2.imageset/Planet2.png
  Resources/Assets.xcassets/Planet3.imageset/Contents.json
  Resources/Assets.xcassets/Planet3.imageset/Planet3.png
  Resources/Assets.xcassets/Planet4.imageset/Contents.json
  Resources/Assets.xcassets/Planet4.imageset/Planet4.png
  Sources/Data/Planet.swift
  Sources/Data/User.swift
  Sources/Presenter/Home/HomeDTO/InquiryMyCouresDTO.swift
  Sources/Presenter/Home/MyHome/ConstellationCollectionViewCell.swift
  Sources/Presenter/Home/MyHome/CustomLayoutDelegate.swift
  Sources/Presenter/Home/MyHome/HomeAPIService.swift
  Sources/Presenter/Home/MyHome/View/CarouselCollectionView.swift
  Sources/Presenter/Home/MyHome/View/ConstellationCollectionViewCell.swift
  Sources/Presenter/Home/MyHome/View/CourseCollectionViewCell.swift
  Sources/Presenter/Home/MyHome/View/HomeDetailView.swift
  Sources/Presenter/Home/MyHome/View/RandomPlanetView.swift
  Sources/Presenter/Home/MyHome/ViewController/CoursesViewController.swift
  Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
  Sources/Presenter/Home/MyHome/ViewController/RandomPlanetViewController.swift
  Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
  Sources/Utility/Class/StarMaker.swift
Labels: 🌳Youth, ✨기능 추가, Main Task

#106 ✨코스 등록 API 호출
  .swiftlint.yml
  Sources/Data/AddCourse/AddCourseDTO.swift
  Sources/Data/AddCourse/AddCourseError.swift
  Sources/Data/AddCourse/AddCourseRepositoryImpl.swift
  Sources/Data/AddCourse/AddCourseResponse.swift
  Sources/Domain/AddCourse/AddCourseUseCase.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewController.swift
  Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewModel.swift
  Sources/Presenter/Home/AddCourse/AddCourseCoordinator.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewController.swift
  Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewModel.swift
Labels: 🎹Charlie, ✨기능 추가, Sub Task
